### ISSUE TITLE
Fix 'held' notebook for DAE

### ISSUE THREAD

**Issue by dangunter** [IDAES/examples#18] opened 2023-02-23 21:38 UTC
https://github.com/IDAES/examples/tree/main/idaes_examples/notebooks/held/dae/pets_pid_src.ipynb
and accompanying `pid.py` in same directory.

in cell 5:
```
m = pid.create_model(
    time_set=[0, 12],
    nfe=1,
    calc_integ=True,
)
```
the following error occurs:
```
2023-02-19 09:47:01 [ERROR] idaes.core.base.process_block: Failure in build: fs.ctrl
Traceback (most recent call last):
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\idaes\core\base\process_block.py", line 39, in _rule_default
    b.build()
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\idaes\models\control\controller.py", line 198, in build
    super().build()
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\idaes\core\base\unit_model.py", line 106, in build
    super(UnitModelBlockData, self).build()
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\idaes\core\base\process_base.py", line 120, in build
    self._get_config_args()
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\idaes\core\base\process_base.py", line 241, in _get_config_args
    self.config = self.CONFIG(kwargs)
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\pyomo\common\config.py", line 1353, in __call__
    ans.set_value(value)
  File "C:\Users\dang\miniconda3\envs\idaes_main_py310\lib\site-packages\pyomo\common\config.py", line 2307, in set_value
    raise ValueError(
ValueError: key 'type' not defined for ConfigDict '' and implicit (undefined) keys are not allowed
ERROR: Constructing component 'fs.ctrl' from data=None failed: ValueError: key
    'type' not defined for ConfigDict '' and implicit (undefined) keys are not
    allowed
```

**Comment by blnicho** [comment] 2023-02-23 21:47
I think this might be a duplicate of https://github.com/IDAES/examples/issues/15. This looks like the error that @eslickj just fixed in https://github.com/IDAES/examples-pse/pull/175/files

**Closed** 2023-04-04 17:17 UTC
Labels: Priority:Normal
